Repository kkb00714/ManiToOne, pull requests merged in 2024-12, with the labels that each got.

#33 Feat: 게시글 작성 기능
  src/main/java/com/finalproject/manitoone/controller/PostController.java
  src/main/java/com/finalproject/manitoone/domain/Post.java
  src/main/java/com/finalproject/manitoone/domain/PostImage.java
  src/main/java/com/finalproject/manitoone/domain/dto/AddPostRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/PostImageResponseDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/PostResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/PostImageRepository.java
  src/main/java/com/finalproject/manitoone/repository/PostRepository.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/resources/templates/postModal.html
Labels: 💫 feat

#42 좋아요 누른 게시글, 특정 유저의 게시글 가져오기
  src/main/java/com/finalproject/manitoone/constants/IllegalActionMessages.java
  src/main/java/com/finalproject/manitoone/controller/PostController.java
  src/main/java/com/finalproject/manitoone/domain/Post.java
  src/main/java/com/finalproject/manitoone/domain/UserPostLike.java
  src/main/java/com/finalproject/manitoone/domain/UserPostLikeId.java
  src/main/java/com/finalproject/manitoone/dto/post/PostViewResponseDto.java
  src/main/java/com/finalproject/manitoone/dto/postimage/PostImageResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/PostImageRepository.java
  src/main/java/com/finalproject/manitoone/repository/PostRepository.java
  src/main/java/com/finalproject/manitoone/repository/UserPostLikeRepository.java
  src/main/java/com/finalproject/manitoone/repository/UserRepository.java
  src/main/java/com/finalproject/manitoone/service/FollowService.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
Labels: ♻ refactor, 🔥 backend

#43 feat : 비밀번호 암호화 기능 및 이메일 인증 기능 추가
  build.gradle
  src/main/java/com/finalproject/manitoone/config/SecurityConfig.java
  src/main/java/com/finalproject/manitoone/controller/UserAuthController.java
  src/main/java/com/finalproject/manitoone/controller/view/MailController.java
  src/main/java/com/finalproject/manitoone/domain/dto/UserSignUpDTO.java
  src/main/java/com/finalproject/manitoone/service/MailService.java
  src/main/java/com/finalproject/manitoone/service/UserAuthService.java
  src/main/resources/application.properties
Labels: ♻ refactor, 💫 feat, 🔥 backend

#44 알림 관련 백엔드 프론트 구현
  src/main/java/com/finalproject/manitoone/constants/NotiType.java
  src/main/java/com/finalproject/manitoone/controller/api/NotificationApiController.java
  src/main/java/com/finalproject/manitoone/controller/view/NotificationViewController.java
  src/main/java/com/finalproject/manitoone/domain/Notification.java
  src/main/java/com/finalproject/manitoone/domain/dto/AddNotificationRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/NotificationResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/NotificationRepository.java
  src/main/java/com/finalproject/manitoone/service/NotificationService.java
  src/main/resources/static/img/defaultProfile.png
  src/main/resources/static/script/common.js
  src/main/resources/templates/fragments/content/notification.html
Labels: 💫 feat, 🔥 backend

#45 Feat: 게시글 작성 프론트
  src/main/java/com/finalproject/manitoone/controller/PostController.java
  src/main/resources/static/script/newPost.js
  src/main/resources/templates/fragments/modals/new-post-modal.html
  src/main/resources/templates/index.html
  src/main/resources/templates/postModal.html
Labels: 💫 feat, 🌈 frontend

#48 Dto 생성 방식 변경
  src/main/java/com/finalproject/manitoone/domain/Post.java
  src/main/java/com/finalproject/manitoone/domain/User.java
  src/main/java/com/finalproject/manitoone/dto/post/PostViewResponseDto.java
  src/main/java/com/finalproject/manitoone/dto/user/UserInformationResponseDto.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/java/com/finalproject/manitoone/service/UserService.java
Labels: ♻ refactor

#52 refactor : 알림 프론트 구조 변경 및 백엔드 리팩토링
  src/main/java/com/finalproject/manitoone/controller/view/NotificationViewController.java
  src/main/java/com/finalproject/manitoone/domain/Notification.java
  src/main/java/com/finalproject/manitoone/domain/dto/NotificationResponseDto.java
  src/main/java/com/finalproject/manitoone/service/NotificationService.java
  src/main/java/com/finalproject/manitoone/util/DataUtil.java
  src/main/java/com/finalproject/manitoone/util/NotificationUtil.java
  src/main/resources/static/script/common.js
  src/main/resources/static/script/notification.js
  src/main/resources/static/style/notification.css
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/fragments/content/notification.html
  src/main/resources/templates/pages/notifications.html
Labels: ♻ refactor, 🖥 work in progress, 🔥 backend

#54 마이페이지, 타 유저 페이지 작업 및 DTO 변동
  src/main/java/com/finalproject/manitoone/controller/FollowController.java
  src/main/java/com/finalproject/manitoone/controller/PostController.java
  src/main/java/com/finalproject/manitoone/controller/ProfileViewController.java
  src/main/java/com/finalproject/manitoone/domain/AiPostLog.java
  src/main/java/com/finalproject/manitoone/domain/ReplyPost.java
  src/main/java/com/finalproject/manitoone/dto/post/PostViewResponseDto.java
  src/main/java/com/finalproject/manitoone/dto/replypost/ReplyPostResponseDto.java
  src/main/java/com/finalproject/manitoone/dto/user/UserInformationResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/ReplyPostRepository.java
  src/main/java/com/finalproject/manitoone/service/FollowService.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/java/com/finalproject/manitoone/service/UserService.java
  src/main/resources/templates/profile.html
Labels: ♻ refactor, 🌈 frontend, 🔥 backend

#53 feat : 로그인 및 비밀번호 찾기 구현
  src/main/java/com/finalproject/manitoone/config/SecurityConfig.java
  src/main/java/com/finalproject/manitoone/constants/IllegalActionMessages.java
  src/main/java/com/finalproject/manitoone/controller/UserAuthController.java
  src/main/java/com/finalproject/manitoone/controller/api/UserAuthController.java
  src/main/java/com/finalproject/manitoone/controller/view/MailController.java
  src/main/java/com/finalproject/manitoone/controller/view/UserAuthViewController.java
  src/main/java/com/finalproject/manitoone/domain/User.java
  src/main/java/com/finalproject/manitoone/domain/dto/UserLoginRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/UserLoginResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/UserRepository.java
  src/main/java/com/finalproject/manitoone/service/MailService.java
  src/main/java/com/finalproject/manitoone/service/UserAuthService.java
Labels: ♻ refactor, 💫 feat, 🔥 backend

#62 Feat: 게시글 삭제, 숨기기, 좋아요 백엔드
  src/main/java/com/finalproject/manitoone/constants/IllegalActionMessages.java
  src/main/java/com/finalproject/manitoone/controller/api/PostController.java
  src/main/java/com/finalproject/manitoone/domain/Post.java
  src/main/java/com/finalproject/manitoone/domain/dto/AddPostRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/PostResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/PostImageRepository.java
  src/main/java/com/finalproject/manitoone/repository/PostRepository.java
  src/main/java/com/finalproject/manitoone/repository/ReplyPostRepository.java
  src/main/java/com/finalproject/manitoone/repository/UserPostLikeRepository.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
Labels: 💫 feat, 🖥 work in progress, 🔥 backend

#60 마니또 편지 생성, 조회, 신고, 답장 작업
  src/main/java/com/finalproject/manitoone/constants/ManitoErrorMessages.java
  src/main/java/com/finalproject/manitoone/controller/ManitoController.java
  src/main/java/com/finalproject/manitoone/domain/ManitoLetter.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoAnswerRequestDto.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoLetterRequestDto.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoLetterResponseDto.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoPageResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/ManitoLetterRepository.java
  src/main/java/com/finalproject/manitoone/service/ManitoService.java
  src/main/java/com/finalproject/manitoone/util/ManitoLetterParser.java
  src/main/java/com/finalproject/manitoone/util/TimeFormatter.java
Labels: 💫 feat, 🔥 backend

#59 마이페이지 및 타 유저 페이지 상세 구현
  src/main/resources/static/script/profile.js
  src/main/resources/static/style/profile.css
  src/main/resources/templates/profile.html
Labels: ♻ refactor, 🌈 frontend, 🖥 work in progress

#68 Feat: 게시글 신고 기능 (백엔드)
  src/main/java/com/finalproject/manitoone/constants/IllegalActionMessages.java
  src/main/java/com/finalproject/manitoone/constants/ReportObjectType.java
  src/main/java/com/finalproject/manitoone/constants/ReportType.java
  src/main/java/com/finalproject/manitoone/controller/api/PostController.java
  src/main/java/com/finalproject/manitoone/domain/Report.java
  src/main/java/com/finalproject/manitoone/domain/dto/ReportResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/ManitoLetterRepository.java
  src/main/java/com/finalproject/manitoone/repository/ReportRepository.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
Labels: 💫 feat, 🖥 work in progress, 🔥 backend

#67 어드민 회원 관련 페이징, 검색, 정보 수정(진행중)
  build.gradle
  src/main/java/com/finalproject/manitoone/config/QueryDslConfig.java
  src/main/java/com/finalproject/manitoone/constants/Role.java
  src/main/java/com/finalproject/manitoone/controller/api/AdminApiController.java
  src/main/java/com/finalproject/manitoone/controller/view/AdminViewController.java
  src/main/java/com/finalproject/manitoone/domain/dto/admin/UserProfileRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/admin/UserSearchRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/admin/UserSearchResponseDto.java
  src/main/java/com/finalproject/manitoone/service/AdminService.java
  src/main/resources/static/images/admin/admin_banner.png
  src/main/resources/static/images/admin/next.png
  src/main/resources/static/images/admin/next_disabled.png
  src/main/resources/static/images/admin/next_group.png
  src/main/resources/static/images/admin/next_group_disabled.png
  src/main/resources/static/images/admin/previous.png
  src/main/resources/static/images/admin/previous_disabled.png
  src/main/resources/static/images/admin/previous_group.png
  src/main/resources/static/images/admin/previous_group_disabled.png
  src/main/resources/static/script/admin/adminUser.js
  src/main/resources/static/style/adminCommon.css
  src/main/resources/static/style/adminUser.css
  src/main/resources/static/style/reset.css
  src/main/resources/templates/fragments/admin/adminHeader.html
  src/main/resources/templates/fragments/admin/adminNav.html
  src/main/resources/templates/fragments/admin/modals/user-modal.html
  src/main/resources/templates/pages/admin/adminIndex.html
  src/main/resources/templates/pages/admin/adminUser.html
Labels: 💫 feat, 🖥 work in progress, 🔥 backend

#69 feat : 회원가입 및 로그인 페이지 프론트 연동
  src/main/java/com/finalproject/manitoone/controller/view/MailViewController.java
  src/main/java/com/finalproject/manitoone/repository/UserRepository.java
  src/main/java/com/finalproject/manitoone/service/MailService.java
  src/main/resources/static/style/email-auth.css
  src/main/resources/static/style/find-password.css
  src/main/resources/static/style/sign-up.css
  src/main/resources/templates/pages/auth/email-auth.html
  src/main/resources/templates/pages/auth/find-password-after.html
  src/main/resources/templates/pages/auth/find-password.html
  src/main/resources/templates/pages/auth/sign-in.html
  src/main/resources/templates/pages/auth/sign-up.html
Labels: ♻ refactor, 💫 feat, 🌈 frontend

#73 feat : 회원 탈퇴 기능 추가 및 회원가입 & 로그인 부분 오류 수정
  build.gradle
  src/main/java/com/finalproject/manitoone/config/SecurityConfig.java
  src/main/java/com/finalproject/manitoone/controller/api/UserAuthController.java
  src/main/java/com/finalproject/manitoone/domain/User.java
  src/main/java/com/finalproject/manitoone/domain/dto/CustomOAuth2User.java
  src/main/java/com/finalproject/manitoone/domain/dto/OAuth2Response.java
  src/main/java/com/finalproject/manitoone/domain/dto/admin/GoogleResponse.java
  src/main/java/com/finalproject/manitoone/service/CustomOAuth2UserService.java
  src/main/java/com/finalproject/manitoone/service/UserAuthService.java
  src/main/resources/application.properties
  src/main/resources/static/style/sign-up.css
  src/main/resources/templates/pages/auth/email-auth.html
  src/main/resources/templates/pages/auth/find-password-after.html
  src/main/resources/templates/pages/auth/find-password.html
  src/main/resources/templates/pages/auth/sign-in.html
  src/main/resources/templates/pages/auth/sign-up.html
Labels: ♻ refactor, 💫 feat, 🌈 frontend, 🔥 backend

#74 Feature : 마니또 페이지 프론트 추가 구현
  src/main/java/com/finalproject/manitoone/constants/ManitoErrorMessages.java
  src/main/java/com/finalproject/manitoone/controller/ManitoController.java
  src/main/java/com/finalproject/manitoone/controller/WebTestController.java
  src/main/java/com/finalproject/manitoone/controller/view/ManitoViewController.java
  src/main/java/com/finalproject/manitoone/domain/ManitoLetter.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoAnswerRequestDto.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoLetterRequestDto.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoLetterResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/ManitoLetterRepository.java
  src/main/java/com/finalproject/manitoone/service/ManitoService.java
  src/main/java/com/finalproject/manitoone/util/ManitoLetterParser.java
  src/main/java/com/finalproject/manitoone/util/TimeFormatter.java
  src/main/resources/static/script/common.js
  src/main/resources/static/script/manito.js
  src/main/resources/static/style/common.css
  src/main/resources/templates/fragments/common/common-layout.html
  src/main/resources/templates/fragments/common/manito-letter-box.html
  src/main/resources/templates/fragments/common/manito-letter.html
  src/main/resources/templates/fragments/content/manito.html
  src/main/resources/templates/fragments/content/timeline.html
  src/main/resources/templates/fragments/modals/manito-confirm-message-modal.html
  src/main/resources/templates/fragments/modals/manito-letter-modal.html
  src/main/resources/templates/fragments/modals/manito-letter-reply-modal.html
  src/main/resources/templates/index.html
Labels: 🌈 frontend

#80 앨런 호출 기능 및 일부 코드에 비동기 처리 반영
  src/main/java/com/finalproject/manitoone/ManiToOneApplication.java
  src/main/java/com/finalproject/manitoone/controller/UserController.java
  src/main/java/com/finalproject/manitoone/controller/api/PostController.java
  src/main/java/com/finalproject/manitoone/repository/AiPostLogRepository.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/java/com/finalproject/manitoone/util/AlanUtil.java
Labels: ⚙ chore, 💫 feat, 🔥 backend

#87 어드민 게시글 관리 백엔드 프론트엔드 구현
  src/main/java/com/finalproject/manitoone/controller/api/AdminApiController.java
  src/main/java/com/finalproject/manitoone/controller/view/AdminViewController.java
  src/main/java/com/finalproject/manitoone/domain/Post.java
  src/main/java/com/finalproject/manitoone/domain/dto/admin/PostSearchRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/admin/PostSearchResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/AiPostLogRepository.java
  src/main/java/com/finalproject/manitoone/repository/ManitoLetterRepository.java
  src/main/java/com/finalproject/manitoone/service/AdminService.java
  src/main/java/com/finalproject/manitoone/util/FileUtil.java
  src/main/resources/static/script/admin/adminPost.js
  src/main/resources/static/style/adminCommon.css
  src/main/resources/static/style/adminPost.css
  src/main/resources/static/style/adminUser.css
  src/main/resources/templates/pages/admin/adminPost.html
Labels: 💫 feat, 🖥 work in progress, 🔥 backend

#90 프로필 상세 구현 작업
  src/main/java/com/finalproject/manitoone/controller/FollowController.java
  src/main/java/com/finalproject/manitoone/controller/ProfileViewController.java
  src/main/java/com/finalproject/manitoone/controller/api/PostController.java
  src/main/java/com/finalproject/manitoone/dto/user/UserInformationResponseDto.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/resources/static/script/profile.js
  src/main/resources/templates/profile.html
Labels: 💫 feat, 🌈 frontend, 🔥 backend

#99 팔로우 관련 로직 수정 및 뷰 페이지 일부 수정
  src/main/java/com/finalproject/manitoone/controller/ProfileViewController.java
  src/main/java/com/finalproject/manitoone/domain/Follow.java
  src/main/java/com/finalproject/manitoone/repository/FollowRepository.java
  src/main/java/com/finalproject/manitoone/service/FollowService.java
  src/main/resources/static/script/profile.js
  src/main/resources/templates/fragments/modals/follow-list-modal.html
  src/main/resources/templates/profile.html
Labels: 🕷 bug, 🌈 frontend, 🔥 backend

#101 [ FEAT ] 알림 실시간 소켓 연결
  build.gradle
  src/main/java/com/finalproject/manitoone/aop/AlarmHandler.java
  src/main/java/com/finalproject/manitoone/config/WebSocketConfig.java
  src/main/java/com/finalproject/manitoone/constants/IllegalActionMessages.java
  src/main/java/com/finalproject/manitoone/controller/api/NotificationApiController.java
  src/main/java/com/finalproject/manitoone/controller/api/UserAuthController.java
  src/main/java/com/finalproject/manitoone/controller/view/NotificationViewController.java
  src/main/java/com/finalproject/manitoone/domain/Notification.java
  src/main/java/com/finalproject/manitoone/domain/dto/AddNotificationRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/NotificationResponseDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/UserLoginResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/NotificationRepository.java
  src/main/java/com/finalproject/manitoone/service/NotificationService.java
  src/main/java/com/finalproject/manitoone/util/NotificationUtil.java
  src/main/resources/static/script/header.js
  src/main/resources/static/script/notification.js
  src/main/resources/static/script/socket.js
  src/main/resources/static/style/notification.css
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/fragments/content/notification.html
  src/main/resources/templates/pages/auth/sign-in.html
Labels: 🌈 frontend, 🖥 work in progress, 🔥 backend

#102 [ FEATURE ] : 마니또 편지, 답장 신고 및 편지함 연결
  src/main/java/com/finalproject/manitoone/constants/ManitoErrorMessages.java
  src/main/java/com/finalproject/manitoone/constants/ReportObjectType.java
  src/main/java/com/finalproject/manitoone/controller/ManitoController.java
  src/main/java/com/finalproject/manitoone/controller/TimelineController.java
  src/main/java/com/finalproject/manitoone/controller/view/ManitoViewController.java
  src/main/java/com/finalproject/manitoone/controller/view/WebViewController.java
  src/main/java/com/finalproject/manitoone/domain/ManitoLetter.java
  src/main/java/com/finalproject/manitoone/domain/dto/ReportRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/admin/ReportStatusResponseDto.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoLetterRequestDto.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoLetterResponseDto.java
  src/main/java/com/finalproject/manitoone/service/ManitoService.java
  src/main/java/com/finalproject/manitoone/service/ReportService.java
  src/main/java/com/finalproject/manitoone/util/TimeFormatter.java
  src/main/resources/static/script/common.js
  src/main/resources/static/script/manito.js
  src/main/resources/static/style/common.css
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/fragments/common/right-section.html
  src/main/resources/templates/fragments/content/manito.html
  src/main/resources/templates/fragments/modals/manito-letter-reply-sent-modal.html
  src/main/resources/templates/fragments/modals/report-modal.html
  src/main/resources/templates/pages/notifications.html
  src/main/resources/templates/profile.html
Labels: 💫 feat, 🌈 frontend, 🔥 backend

#108 프로필 상세 구현
  src/main/java/com/finalproject/manitoone/service/FollowService.java
  src/main/resources/static/script/profile.js
  src/main/resources/templates/fragments/modals/profile-update-modal.html
Labels: 🌈 frontend

#100 fix : 로그인 시 세션에 값이 저장되지 않던 문제 수정
  src/main/java/com/finalproject/manitoone/config/CorsConfig.java
  src/main/java/com/finalproject/manitoone/config/CustomAuthenticationSuccessHandler.java
  src/main/java/com/finalproject/manitoone/config/PasswordEncoderConfig.java
  src/main/java/com/finalproject/manitoone/config/SecurityConfig.java
  src/main/java/com/finalproject/manitoone/constants/IllegalActionMessages.java
  src/main/java/com/finalproject/manitoone/controller/api/UserAuthController.java
  src/main/java/com/finalproject/manitoone/controller/view/UserAuthViewController.java
  src/main/java/com/finalproject/manitoone/domain/User.java
  src/main/java/com/finalproject/manitoone/domain/dto/PrincipalDetails.java
  src/main/java/com/finalproject/manitoone/repository/UserRepository.java
  src/main/java/com/finalproject/manitoone/service/CustomOAuth2UserService.java
  src/main/java/com/finalproject/manitoone/service/UserAuthService.java
  src/main/resources/static/style/sign-up.css
  src/main/resources/templates/pages/auth/oauth-login-failure.html
  src/main/resources/templates/pages/auth/sign-in.html
  src/main/resources/templates/pages/auth/sign-up.html
Labels: 🕷 bug, 🖥 work in progress, 🔥 backend

#112 feat : OAuth2 기능 구현 및 세션에 값 저장 기능 추가
  src/main/java/com/finalproject/manitoone/config/SecurityConfig.java
  src/main/java/com/finalproject/manitoone/controller/api/UserAuthController.java
  src/main/java/com/finalproject/manitoone/controller/view/UserAuthViewController.java
  src/main/java/com/finalproject/manitoone/controller/view/WebViewController.java
  src/main/java/com/finalproject/manitoone/domain/User.java
  src/main/java/com/finalproject/manitoone/domain/dto/AuthUpdateDto.java
  src/main/java/com/finalproject/manitoone/service/CustomOAuth2UserService.java
  src/main/java/com/finalproject/manitoone/service/UserAuthService.java
  src/main/resources/static/style/additional-info.css
  src/main/resources/static/style/loading.css
  src/main/resources/static/style/password-view.css
  src/main/resources/templates/index.html
  src/main/resources/templates/pages/auth/additional-info.html
  src/main/resources/templates/pages/auth/email-auth.html
  src/main/resources/templates/pages/auth/find-password.html
  src/main/resources/templates/pages/auth/sign-in.html
  src/main/resources/templates/pages/auth/sign-up.html
Labels: 💫 feat, 🌈 frontend, 🖥 work in progress, 🔥 backend

#118 [ FEATURE] : ManitoMatches 엔티티 추가에 따른 기능 추가 및 마니또 기능 전체 리팩토링
  src/main/java/com/finalproject/manitoone/aop/GlobalExceptionHandler.java
  src/main/java/com/finalproject/manitoone/constants/IllegalActionMessages.java
  src/main/java/com/finalproject/manitoone/constants/ManitoErrorMessages.java
  src/main/java/com/finalproject/manitoone/constants/MatchStatus.java
  src/main/java/com/finalproject/manitoone/controller/ManitoController.java
  src/main/java/com/finalproject/manitoone/controller/TimelineController.java
  src/main/java/com/finalproject/manitoone/controller/api/SessionApiController.java
  src/main/java/com/finalproject/manitoone/controller/view/ManitoViewController.java
  src/main/java/com/finalproject/manitoone/controller/view/WebViewController.java
  src/main/java/com/finalproject/manitoone/domain/ManitoLetter.java
  src/main/java/com/finalproject/manitoone/domain/ManitoMatches.java
  src/main/java/com/finalproject/manitoone/domain/Post.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoLetterRequestDto.java
  src/main/java/com/finalproject/manitoone/dto/manito/ManitoMatchResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/ManitoLetterRepository.java
  src/main/java/com/finalproject/manitoone/repository/ManitoMatchesRepository.java
  src/main/java/com/finalproject/manitoone/repository/PostRepository.java
  src/main/java/com/finalproject/manitoone/service/ManitoMatchesService.java
  src/main/java/com/finalproject/manitoone/service/ManitoService.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/java/com/finalproject/manitoone/service/ReportService.java
  src/main/resources/static/script/common.js
  src/main/resources/static/script/manito.js
  src/main/resources/static/script/timeline.js
  src/main/resources/static/style/common.css
  src/main/resources/templates/fragments/content/manito.html
  src/main/resources/templates/fragments/modals/manito-confirm-message-modal.html
  src/main/resources/templates/fragments/modals/manito-letter-modal.html
  src/main/resources/templates/fragments/modals/manito-letter-reply-modal.html
  src/main/resources/templates/fragments/modals/new-post-modal.html
  src/main/resources/templates/index.html
  src/main/resources/templates/pages/manito.html
  src/main/resources/templates/pages/notifications.html
  src/main/resources/templates/profile.html
Labels: ♻ refactor, 💫 feat, 🌈 frontend, 🔥 backend

#133 프론트 피드백 받은 부분 수정
  src/main/java/com/finalproject/manitoone/controller/ProfileViewController.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/resources/static/script/profile.js
  src/main/resources/static/style/profile-password-view.css
  src/main/resources/templates/fragments/modals/follow-list-modal.html
  src/main/resources/templates/fragments/modals/profile-update-modal.html
  src/main/resources/templates/profile.html
Labels: 🌈 frontend, 🎨 UI, 🔥 backend

#134 [ FEATURE ] : 편지, 게시글 작성 모달에서 실시간으로 글자수 세기 기능
  src/main/java/com/finalproject/manitoone/repository/ManitoMatchesRepository.java
  src/main/java/com/finalproject/manitoone/service/ManitoMatchesService.java
  src/main/resources/static/script/common.js
  src/main/resources/static/script/manito.js
  src/main/resources/static/style/common.css
  src/main/resources/templates/fragments/modals/manito-letter-modal.html
  src/main/resources/templates/fragments/modals/new-post-modal.html
  src/main/resources/templates/index.html
Labels: 💫 feat, 🌈 frontend

#132 feat : 각 페이지 별 필요한 보안사항 추가 및 마무리 작업 진행
  src/main/java/com/finalproject/manitoone/aop/CustomAuthenticationSuccessHandler.java
  src/main/java/com/finalproject/manitoone/config/SecurityConfig.java
  src/main/java/com/finalproject/manitoone/controller/api/UserAuthController.java
  src/main/java/com/finalproject/manitoone/controller/view/UserAuthViewController.java
  src/main/java/com/finalproject/manitoone/domain/dto/AuthUpdateDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/PrincipalDetails.java
  src/main/java/com/finalproject/manitoone/domain/dto/UserSignUpDTO.java
  src/main/java/com/finalproject/manitoone/service/CustomOAuth2UserService.java
  src/main/resources/static/script/header.js
  src/main/resources/static/style/tooltip.css
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/pages/auth/access-deny.html
  src/main/resources/templates/pages/auth/additional-info.html
  src/main/resources/templates/pages/auth/find-password.html
  src/main/resources/templates/pages/auth/sign-in.html
  src/main/resources/templates/pages/auth/sign-up.html
Labels: 🕷 bug, ⚙ chore, ♻ refactor, 💫 feat, 🌈 frontend, 🔥 backend

#135 [ Feat ] 게시글 & 답글 작성, 수정, 숨기기, 삭제하기, 신고하기
  src/main/java/com/finalproject/manitoone/constants/IllegalActionMessages.java
  src/main/java/com/finalproject/manitoone/controller/api/PostController.java
  src/main/java/com/finalproject/manitoone/controller/api/ReplyController.java
  src/main/java/com/finalproject/manitoone/controller/view/PostViewController.java
  src/main/java/com/finalproject/manitoone/controller/view/WebViewController.java
  src/main/java/com/finalproject/manitoone/domain/ReplyPost.java
  src/main/java/com/finalproject/manitoone/domain/dto/AddPostRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/PostResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/NotificationRepository.java
  src/main/java/com/finalproject/manitoone/repository/PostRepository.java
  src/main/java/com/finalproject/manitoone/repository/ReplyPostRepository.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/java/com/finalproject/manitoone/service/ReplyService.java
  src/main/resources/static/script/post.js
  src/main/resources/static/style/post.css
  src/main/resources/templates/fragments/modals/new-post-modal.html
  src/main/resources/templates/index.html
  src/main/resources/templates/pages/post/postDetail.html
  src/main/resources/templates/pages/post/replyDetail.html
Labels: 💫 feat, 🌈 frontend, 🖥 work in progress, 🔥 backend

#142 application.properties 암호화
  build.gradle
  src/main/java/com/finalproject/manitoone/config/JasyptConfigAES.java
  src/main/java/com/finalproject/manitoone/controller/api/UserSearchController.java
  src/main/java/com/finalproject/manitoone/dto/user/MainUserSearchResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/UserRepository.java
  src/main/java/com/finalproject/manitoone/service/UserSearchService.java
  src/main/resources/application.properties
  src/main/resources/static/script/userSearch.js
  src/main/resources/static/style/reset.css
  src/main/resources/static/style/userSearch.css
  src/main/resources/templates/fragments/common/right-section.html
Labels: 🔥 backend

#139 프로필 상세 구현 및 게시물 관련 (좋아요, 숨기기) 기능 개선
  src/main/java/com/finalproject/manitoone/controller/FollowController.java
  src/main/java/com/finalproject/manitoone/repository/UserPostLikeRepository.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/resources/static/script/profile.js
  src/main/resources/static/style/common.css
  src/main/resources/templates/fragments/modals/profile-update-modal.html
  src/main/resources/templates/profile.html
Labels: 💫 feat, 🌈 frontend, 🔥 backend

#164 [ Feat ] 게시글 & 답글 작성, 수정
  src/main/java/com/finalproject/manitoone/constants/IllegalActionMessages.java
  src/main/java/com/finalproject/manitoone/controller/api/PostController.java
  src/main/java/com/finalproject/manitoone/controller/api/ReplyController.java
  src/main/java/com/finalproject/manitoone/controller/view/PostViewController.java
  src/main/java/com/finalproject/manitoone/domain/dto/AddPostRequestDto.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/java/com/finalproject/manitoone/service/ReplyService.java
  src/main/resources/static/script/post.js
  src/main/resources/static/style/post.css
  src/main/resources/templates/fragments/modals/new-post-modal.html
  src/main/resources/templates/pages/post/postDetail.html
  src/main/resources/templates/pages/post/replyDetail.html
Labels: 💫 feat, 🌈 frontend, 🖥 work in progress, 🔥 backend

#175 어드민 페이지 회원 관리 프로필 수정 변경
  src/main/java/com/finalproject/manitoone/controller/api/AdminApiController.java
  src/main/java/com/finalproject/manitoone/service/AdminService.java
  src/main/java/com/finalproject/manitoone/service/S3Service.java
  src/main/resources/static/script/admin/adminUser.js
Labels: 💫 feat, 🌈 frontend, 🔥 backend

#176 어드민 유저 관리 updateUser 에러 수정
  src/main/resources/static/script/admin/adminUser.js
Labels: 🌈 frontend

#177 feat : 프론트에서 유저 프로필 이미지 수정 기능 추가
  src/main/java/com/finalproject/manitoone/controller/api/S3UploadController.java
  src/main/java/com/finalproject/manitoone/controller/api/UserAuthController.java
  src/main/resources/static/script/profile.js
  src/main/resources/static/style/common.css
  src/main/resources/templates/profile.html
Labels: ⚙ chore, 🌈 frontend

#178 fix: 좋아요 취소 후 다시 좋아요가 안되는 오류 수정
  src/main/java/com/finalproject/manitoone/service/PostService.java
Labels: 🕷 bug, 🔥 backend

#181 프로필 페이지에서 답글을 남기는 기능 추가
  src/main/resources/static/script/profile.js
  src/main/resources/templates/fragments/modals/reply-post-modal.html
  src/main/resources/templates/profile.html
Labels: 💫 feat, 🌈 frontend

#189 [ Fix ] conflict 해결
  src/main/resources/static/script/post.js
Labels: 🕷 bug

#204 docs: README.md 추가
  README.md
Labels: 📚 docs

#205 docs: README.md 수정
  README.md
Labels: 📚 docs

#206 docs: README.md 표 수정
  README.md
Labels: 📚 docs

#207 docs: README.md 표 수정
  README.md
Labels: 📚 docs

#208 docs: README.md 수정
  README.md
Labels: 📚 docs

#211 프로필에서 게시글 조회시 이미지도 같이 조회
  src/main/java/com/finalproject/manitoone/controller/api/FollowController.java
  src/main/java/com/finalproject/manitoone/controller/api/UserController.java
  src/main/java/com/finalproject/manitoone/controller/view/ProfileViewController.java
  src/main/resources/static/script/post.js
  src/main/resources/static/script/profile.js
  src/main/resources/static/style/profile.css
  src/main/resources/static/style/tooltip.css
  src/main/resources/templates/fragments/common/header.html
  src/main/resources/templates/pages/profile.html
  src/test/java/com/finalproject/manitoone/service/FollowServiceTest.java
Labels: ♻ refactor, 🌈 frontend, ✅ test

#210 [ Fix, Refactor ] 게시글 좋아요, 프론트 부분 리팩토링
  src/main/java/com/finalproject/manitoone/controller/api/PostController.java
  src/main/java/com/finalproject/manitoone/controller/api/ReplyController.java
  src/main/java/com/finalproject/manitoone/repository/UserPostLikeRepository.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/resources/static/script/post.js
  src/main/resources/static/style/post.css
  src/main/resources/templates/fragments/modals/new-post-modal.html
  src/main/resources/templates/pages/post/postDetail.html
  src/main/resources/templates/pages/post/replyDetail.html
Labels: ♻ refactor, 🌈 frontend, 🖥 work in progress, 🔥 backend

#216 상대방 프로필 조회 시 나를 팔로우중인지 확인 가능한 문구 추가
  src/main/java/com/finalproject/manitoone/controller/view/ProfileViewController.java
  src/main/resources/static/script/profile.js
  src/main/resources/static/style/profile.css
  src/main/resources/templates/pages/profile.html
Labels: 🌈 frontend, 🎨 UI

#217 팔로우 버튼과 문구에 클래스 추가
  src/main/resources/templates/pages/profile.html
Labels: 🌈 frontend, 🎨 UI

#232 docs: README.md 각 파트부분 추가
  README.md
Labels: 📚 docs

#233 docs: README.md 표 수정
  README.md
Labels: 📚 docs

#236 좋아요 누른 게시글의 프로필 이미지가 내 이미지로 나오던 문제 수정
  src/main/java/com/finalproject/manitoone/service/PostService.java
Labels: 🕷 bug, 🔥 backend

#242 AI 포매팅 수정
  src/main/java/com/finalproject/manitoone/util/AlanUtil.java
  src/main/resources/static/script/post.js
Labels: 🌈 frontend, 🔥 backend

#243 [ Feat, Refactor ] 상세 페이지 수정
  src/main/java/com/finalproject/manitoone/controller/api/PostController.java
  src/main/java/com/finalproject/manitoone/controller/view/PostViewController.java
  src/main/java/com/finalproject/manitoone/domain/dto/PostResponseDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/ReplyResponseDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/UpdatePostRequestDto.java
  src/main/java/com/finalproject/manitoone/repository/UserPostLikeRepository.java
  src/main/java/com/finalproject/manitoone/service/PostService.java
  src/main/java/com/finalproject/manitoone/service/ReplyService.java
  src/main/resources/static/script/post.js
  src/main/resources/static/style/post.css
  src/main/resources/templates/pages/post/postDetail.html
  src/main/resources/templates/pages/post/replyDetail.html
Labels: ♻ refactor, 💫 feat, 🌈 frontend, 🔥 backend

#246 [ Refactor ] 답글 부분 수정
  src/main/resources/templates/pages/post/postDetail.html
Labels: ♻ refactor, 🌈 frontend
