Repository kkb00714/ManiToOne, pull requests merged in 2024-11, with the labels that each got.

#10 chore : Update gradle.yml
  .github/workflows/gradle.yml
Labels: Work In Progress

#26 feat : 회원가입 기능 추가
  build.gradle
  src/main/java/com/finalproject/manitoone/config/SecurityConfig.java
  src/main/java/com/finalproject/manitoone/controller/UserAuthController.java
  src/main/java/com/finalproject/manitoone/domain/User.java
  src/main/java/com/finalproject/manitoone/domain/dto/UserSignUpDTO.java
  src/main/java/com/finalproject/manitoone/repository/UserRepository.java
  src/main/java/com/finalproject/manitoone/service/UserAuthService.java
Labels: 💫 feat

#27 유저끼리의 팔로우 기능 구현 및 유저정보 조회 기능 구현
  build.gradle
  src/main/java/com/finalproject/manitoone/controller/FollowController.java
  src/main/java/com/finalproject/manitoone/controller/UserController.java
  src/main/java/com/finalproject/manitoone/domain/Follow.java
  src/main/java/com/finalproject/manitoone/domain/User.java
  src/main/java/com/finalproject/manitoone/dto/follow/FollowRequestDto.java
  src/main/java/com/finalproject/manitoone/dto/follow/FollowResponseDto.java
  src/main/java/com/finalproject/manitoone/dto/user/UserInformationResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/FollowRepository.java
  src/main/java/com/finalproject/manitoone/repository/UserRepository.java
  src/main/java/com/finalproject/manitoone/service/FollowService.java
  src/main/java/com/finalproject/manitoone/service/UserService.java
Labels: 💫 feat, 🔥 backend

#28 추후 알림이 필요한 부분에 들어갈 알림 생성 기능 구현, 알림 내역 가져오기 진행중
  src/main/java/com/finalproject/manitoone/constants/NotiType.java
  src/main/java/com/finalproject/manitoone/controller/view/NotificationViewController.java
  src/main/java/com/finalproject/manitoone/domain/Notification.java
  src/main/java/com/finalproject/manitoone/domain/dto/AddNotificationRequestDto.java
  src/main/java/com/finalproject/manitoone/domain/dto/NotificationResponseDto.java
  src/main/java/com/finalproject/manitoone/repository/NotificationRepository.java
  src/main/java/com/finalproject/manitoone/service/NotificationService.java
Labels: 💫 feat, 🖥 work in progress, 🔥 backend
